# Generated by Django 6.0 on 2026-01-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_patientadmission_patient_id_bedoccupancylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadmission',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='known_allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='BedStatusLog',
        ),
    ]
