# Generated by Django 6.0 on 2026-01-22 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_patientadmission_blood_group_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_los', models.FloatField(help_text='Predicted Length of Stay in days')),
                ('previous_los', models.FloatField(blank=True, help_text='Previous prediction (for repredictions)', null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('admission_type', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=200, null=True)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
                ('num_procedures', models.IntegerField(blank=True, null=True)),
                ('num_medications', models.IntegerField(blank=True, null=True)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('is_initial_prediction', models.BooleanField(default=True, help_text='True if first prediction, False if reprediction')),
                ('reason_for_change', models.TextField(blank=True, help_text="Why was reprediction needed? (e.g., 'Post-surgery', 'Patient condition improved')")),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_history', to='hospital.patientadmission')),
                ('predicted_by', models.ForeignKey(blank=True, help_text='Staff member who made the prediction', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prediction History',
                'verbose_name_plural': 'Prediction Histories',
                'ordering': ['-predicted_at'],
            },
        ),
    ]
