# Generated by Django 6.0 on 2026-01-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_predictionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='gender_restriction',
            field=models.CharField(choices=[('male', 'Male Only'), ('female', 'Female Only'), ('mixed', 'Mixed Gender')], default='mixed', max_length=10),
        ),
    ]
