# Generated by Django 6.0 on 2026-01-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_ward_gender_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='gender_restriction',
            field=models.CharField(choices=[('male', 'Male Only'), ('female', 'Female Only'), ('mixed', 'Mixed/Any Gender')], default='mixed', max_length=10),
        ),
    ]
