# Generated by Django 6.0 on 2026-03-09 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_bed_gender_restriction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='ward',
            options={'ordering': ['hospital', 'ward_type', 'name']},
        ),
        migrations.AlterField(
            model_name='patientadmission',
            name='patient_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='is_initial_prediction',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='predicted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='previous_los',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='predictionhistory',
            name='reason_for_change',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dischargerecord',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discharge_records', to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='ward',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='hospital.hospital'),
        ),
    ]
