# Generated by Django 6.0 on 2026-03-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_hospital_alter_ward_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadmission',
            name='referral_source',
            field=models.CharField(blank=True, help_text='Name of referring facility or area', max_length=200),
        ),
        migrations.AddField(
            model_name='patientadmission',
            name='referral_type',
            field=models.CharField(blank=True, choices=[('self', 'Self / Walk-in'), ('hospital', 'Another Hospital'), ('clinic', 'Clinic / Polyclinic'), ('community', 'Community Health Centre'), ('other', 'Other')], default='self', max_length=20),
        ),
    ]
