# Generated by Django 6.0 on 2026-03-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_profile_bio_profile_date_of_birth_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadmission',
            name='nhis_status',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
    ]
